### ISSUE TITLE
the turn server maybe not works?

### ISSUE THREAD

**Issue by Jackie2016** [muaz-khan/RTCMultiConnection#135]
Hi,great muaz
i make a experiment of rtcmulticonnection in two client.one is on the network which is symmetric nat ,another is restricted port cone.and now i could not chat in video/audio.i think it is p2p traversal fail.but i check the code.i find as below

` var iceServers = [];
iceServers.push({
url: 'stun:stun.l.google.com:19302'
});

    iceServers.push({
        url: 'stun:stun.anyfirewall.com:3478'
    });

    iceServers.push({
        url: 'turn:turn.bistri.com:80',
        credential: 'homeo',
        username: 'homeo'
    });

    iceServers.push({
        url: 'turn:turn.anyfirewall.com:443?transport=tcp',
        credential: 'webrtc',
        username: 'webrtc'
    });

    connection.iceServers = iceServers;

    connection.rtcConfiguration = {
        iceServers: null,
        iceTransports: 'all', // none || relay || all - ref: http://goo.gl/40I39K
        peerIdentity: false
    };
`
here the code have turn server and i can ping turn.anyfirewall.com successfully and could get turn.bistri.com webpage.i want to know why i could not chat successfully.is the turn server not working?or any errors?
any light would be appreciated.thanks

**Comment by dnish** [comment]
Did you check your WebRTC logs in chrome?

**Comment by muaz-khan** [comment]
XirSys always works however free-account disconnects often. Merely `anyfirewall ` TURN server is **expected** to work. I'll setup a custom TURN server and remove all these 3rd party links (soon).

**Comment by Jackie2016** [comment]
thanks,muaz,when you setup your own turn server,tell me and i could try it.thanks very much.

**Comment by shaitkhan786** [comment]
thanks muaz for all your effort

which turn server you would be implementing. can you share the installation steps

**Comment by Jackie2016** [comment]
coturn is popular,you can google coturn+webrtc.you can get the steps in detail.

**Comment by muaz-khan** [comment]
The TURN-server is running here:

```javascript
connection.iceServers = [];

connection.iceServers.push({
    urls: 'turn:webrtcweb.com:3478',
    username: 'muazkh',
    credential: 'muazkh'
});

connection.iceServers.push({
    urls: 'turns:webrtcweb.com:5349',
    username: 'muazkh',
    credential: 'muazkh'
});

connection.candidates = {
    turn: true, // relay:true or turn:true
    stun: false
};
```

Currently it is listening ports 3478 and 5349 however I'm planning to run on ports 80/443 to make sure it can traverse maximum of the NATs.

**Comment by Jackie2016** [comment]
oh,thanks.but your turn server maybe not work.
i change 
```
        iceServers.push({
            url: 'turn:turn.bistri.com:80',
            credential: 'homeo',
            username: 'homeo'
        });

        iceServers.push({
            url: 'turn:turn.anyfirewall.com:443?transport=tcp',
            credential: 'webrtc',
            username: 'webrtc'
        });
```
to
```
				connection.iceServers.push({
				    url: 'turn:webrtcweb.com:3478',
				    username: 'muazkh',
				    credential: 'muazkh'
				});
				
				connection.iceServers.push({
				    url: 'turn:webrtcweb.com:5349',
				    username: 'muazkh',
				    credential: 'muazkh'
				}); 
```

i get these errors
```
TypeError: connection.iceServers is undefined
setDefaults()             RTCMultiConnection.js:5379
window.RTCMultiConnection()     RTCMultiConnection.js:1003
initRTCMultiConnection()
```
and then the application webpage stops and could not chat successfully.
i am sure i have no firewall to stop it.

**Comment by muaz-khan** [comment]
Now CoTURN is listening both TCP/UDP ports (80/443).

```javascript
// for v2.2.2 (skip xirsys servers)
connection.getExternalIceServers = false;

connection.iceServers = [];

connection.iceServers.push({
    url: 'stun:stun.l.google.com:19302'
});

connection.iceServers.push({
    urls: 'turn:webrtcweb.com:80',
    username: 'muazkh',
    credential: 'muazkh'
});

connection.iceServers.push({
    urls: 'turn:webrtcweb.com:443',
    username: 'muazkh',
    credential: 'muazkh'
});
```

Currently port 443 is listening fake certificate that's why we can't use `turns:`.

**Comment by dnish** [comment]
@muaz-khan But do FF and Chrome even use Turn if it's not encrypted over SSL? I'm just wondering about Chrome, because it forces SSL for camera access and also has the rule that on a encrypted sites all resources need to be called over SSL.

**Comment by shaitkhan786** [comment]
@muaz-khan 

Where can I find instructions to implement my own Turn server?

**Comment by muaz-khan** [comment]
You can try this (2013-old) post:

* https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html

I'll update it for the CoTURN installation steps on Ubuntu/Debian, after fixing `turn:webrtcweb.com:80` auto-disconnection bugs.

**Comment by libuma** [comment]
Dear all, muaz-khan,
I also installed CoTURN, and I'm experiencing auto-disconnection issues. I'm not able to see any related number of connection nor up time. Is this something known and fixed ? Can someone help me regarding this ?

**Comment by Nitishkumar3211** [comment]
@muaz-khan I have implemented turn and stun server as you have implemented in "Video Conference" But I am unable to  get Remote Stream if they are on another network. its work only when end user and me are on same wifi. Please guide .

Thanks in adance

**Comment by ashishbutolajnu16** [comment]
Hi Muaz,
I used you turn server in my webrtc application. They didn't work. I am able to share screening within same wifi but not able to 
share screen on different network. I created my own turn server also but still not able to share screen on different network. Please can you help me in this. session 000000000000000002: user <>: incoming packet message processed, error 401: Unauthorised. This error is logging in my turn server when i connect with my application. Can you help me regarding this. I used your turn server also in my code but they are also not working. Please help me into this
